title: AI Fluency
description: An open-source, micro-learning framework for building AI competency across organizations.
theme: jekyll-theme-hacker

url: "https://briankolowitz.github.io"
baseurl: "/ai-fluency"
